version: '3.8'

services:
  postgres08:
    image: postgres:13
    container_name: postgres08
    ports:
      - "5055:5432"
    environment:
      POSTGRES_DB: staff_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: backend-staff
    ports:
      - "4040:4040"
    depends_on:
      - postgres08

  hr-staff:
    build:
      context: ./HR-staff
    container_name: hr-staff
    ports:
      - "8106:80"
    depends_on:
      - backend

volumes:
  postgres_data:

